### ISSUE TITLE
vCloud Walker to report disk information

### ISSUE THREAD

**Issue by annashipman** [gds-operations/vcloud-walker#101]
It would be great if vCloud Walker reported the following information about the disks belonging to a VM:

- The disk size
- The disk controller used
- The bus and unit set

It's possible to see this information using the UI.

**Comment by deanwilson** [comment]
Thank you for your interest in this project but we now consider it
both feature complete for our own usage and in maintenance mode.
While we will not be investing any more development time in this
project we may still include pull requests.
