### ISSUE TITLE
Storage Profile/Policy only exposed if a vApp/VM already exists

### ISSUE THREAD

**Issue by ajlanghorn** [gds-operations/vcloud-walker#104]
As someone using vCloud Walker to run integration tests against a vCloud environment,
I want vCloud Walker to expose the Storage Profile without a VM having to have been already created inside a pre-existing vApp,
So that I have all the variable values required to be in `vcloud_tools_testing_config/config.yaml` in order to run the integration tests.

**Comment by deanwilson** [comment]
Thank you for your interest in this project but we now consider it
both feature complete for our own usage and in maintenance mode.
While we will not be investing any more development time in this
project we may still include pull requests.

**Comment by ajlanghorn** [comment]
@deanwilson No problem. The issue was raised when I was working on the GOV.UK Infrastructure team. Obviously, I no longer do and I no longer actively use this project.
