### ISSUE TITLE
Issue walking VPNs when configured with no 3rd party peer

### ISSUE THREAD

**Issue by theothertom** [gds-operations/vcloud-walker#106]
We have VPNs configured in VCD to connect to "another network in this organization", rather than with a remote peer and secret. It appears that this breaks vcloud-walker at lib/vcloud/walker/resource/gateway_ipsec_vpn_service.rb:22 as there is no fog_vpn_tunnel[:IpsecVpnThirdPartyPeer][:PeerId].

I found that changing this line to :PeerId => fog_vpn_tunnel[:PeerId] fixed the problem, but I don't think that's going to work for situations where there's a proper VPN, rather than a magical VMware VPN

**Comment by mattbostock** [comment]
Hi @theothertom, did you get chance to test the fix?

**Comment by theothertom** [comment]
Hi,
Seems to work on the 84123826-vpn_fix branch.

Cheers,

Tom

**Comment by mattbostock** [comment]
Thanks @theothertom, I've raised that branch as a PR: #109
