### ISSUE TITLE
Integration tests depend on environment

### ISSUE THREAD

**Issue by annashipman** [gds-operations/vcloud-walker#98]
Most of the time these tests run against an empty environment so test very little. They do not fail if run against an empty environment, but in that case they are testing almost nothing.

In order to test more, they require the environment to be set up as the tests specify (manually).

It would be better if the tests created an environment/tested it was as expected, and then walk that and test more thoroughly.

https://www.pivotaltracker.com/story/show/63371108

**Comment by deanwilson** [comment]
Thank you for your interest in this project but we now consider it
both feature complete for our own usage and in maintenance mode.
While we will not be investing any more development time in this
project we may still include pull requests.
