### ISSUE TITLE
Tests are namespaced incorrectly

### ISSUE THREAD

**Issue by annashipman** [gds-operations/vcloud-walker#99]
The unit tests are namespaced incorrectly.

They add themselves into the module they are testing, like this:

```ruby
module Vcloud
  module Walker
```
And then call that object again explicitly:
```ruby
       result_array = Vcloud::Walker.walk("catalogs")
```

One side-effect of this is it is then possible to refer to objects without namespacing them correctly, which can then get missed out when refactoring.

It would be cleaner and more rspec-ey to do:
```ruby
describe Vcloud::Walker do
…
  it "foo" should
    subject.update(bar)
```

Refactoring the tests like this can make them easier to read, as well as maintain.

Using subject can also make the tests easier to read. However, [you might not want to actually use variable name `subject`](http://blog.davidchelimsky.net/blog/2012/05/13/spec-smell-explicit-use-of-subject/).

Please see [a previous example](https://github.com/gds-operations/vcloud-launcher/pull/29) of where we did this.

This can also be combined with using `let` rather than `before`. See [another example](https://github.com/gds-operations/vcloud-launcher/pull/30) of where we did this.

Further reading:
[DRY up your Rspec test files with subject and let](http://benscheirman.com/2011/05/dry-up-your-rspec-files-with-subject-let-blocks/)
[Rspec before vs let](http://www.launchacademy.com/codecabulary/learn-test-driven-development/rspec/before-vs-let)

**Comment by deanwilson** [comment]
Thank you for your interest in this project but we now consider it
both feature complete for our own usage and in maintenance mode.
While we will not be investing any more development time in this
project we may still include pull requests.
